/**
 * BeTalent Gift Catalog Seed
 * Inserts 50+ premium, music/performance-themed gifts into the Gift table.
 * Safe to run on existing DB: adds new gifts, updates existing by slug.
 *
 * Fields populated: slug, name, icon, animationType, coinCost, rarityTier, isActive
 * (id is auto-generated by Prisma)
 *
 * Run from project root:
 *   npm run db:seed-gifts
 * or:
 *   npx tsx scripts/seed-gifts.ts
 */
import { PrismaClient } from '@prisma/client';
import { giftCatalogToSeedRows } from '../src/constants/giftCatalog';

const prisma = new PrismaClient();

async function main() {
  const rows = giftCatalogToSeedRows();
  if (rows.length < 50) {
    throw new Error(`Gift catalog must have at least 50 gifts. Found: ${rows.length}`);
  }

  let created = 0;
  let updated = 0;
  for (const row of rows) {
    const existing = await prisma.gift.findUnique({ where: { slug: row.slug } });
    if (existing) {
      await prisma.gift.update({
        where: { slug: row.slug },
        data: {
          name: row.name,
          icon: row.icon,
          animationType: row.animationType,
          coinCost: row.coinCost,
          rarityTier: row.rarityTier,
          isActive: row.isActive,
        },
      });
      updated++;
    } else {
      await prisma.gift.create({ data: row });
      created++;
    }
  }

  console.log(`✓ Gift catalog synced: ${created} created, ${updated} updated. Total: ${rows.length}`);
}

main()
  .catch((e) => {
    console.error('Gift seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
